name: Check-In automation

on:
  workflow_dispatch:
  schedule:
    - cron: '57 11 * * *'
    - cron: '58 11 * * *'
    - cron: '59 11 * * *'
    - cron: '0 12 * * *'
    - cron: '1 12 * * *'
    - cron: '2 12 * * *'
    - cron: '3 12 * * *'
    - cron: '4 12 * * *'

jobs:
  
  check-in-automation:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: install dependencies
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libglib2.0-0 libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libx11-6 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 libgbm1 libxcb1 libxkbcommon0 libpango-1.0-0 libcairo2 libasound2
          version: 1.0
    
      - name: Run Checkin-automation
        run: docker run -e TEST_EMAIL=${{ secrets.TEST_EMAIL }} -e TEST_PASSWORD=${{ secrets.TEST_PASSWORD }} ghcr.io/mathieusoysal/42-check-in-automation:latest 
